services:
  db:
    image: postgres:13
    restart: always
    container_name: tiraduvidas_db_homolog
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data-homolog:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout:  5s
      retries: 5
    networks: 
      - internal-homolog

  redis:
    image:  redis:7-alpine
    container_name: tiraduvidas_redis_homolog
    command: redis-server --appendonly yes
    volumes:
      - redis_data_homolog:/data
    restart:  unless-stopped
    networks:
      - internal-homolog

  api:
    build:
      context: ./back-tiraduvidas
      dockerfile: Dockerfile
    image: tiraduvidas-api:homolog
    container_name:  tiraduvidas_api_homolog
    restart: unless-stopped
    environment:
      NODE_ENV: homolog
      APP_PORT: ${APP_PORT}
      APP_NAME:  ${APP_NAME}
      API_PREFIX: ${API_PREFIX}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command:  >
      sh -c "
        echo 'Waiting for database connection...' &&
        while ! nc -z db 5432; do
          sleep 1
        done &&
        echo 'Database connected!' &&
        npm run migration:run &&
        npm run start: prod
      "
    networks:
      - internal-homolog
      - web-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: tiraduvidas-frontend:homolog
    container_name: tiraduvidas_frontend_homolog
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api
    networks:
      - web-network

volumes:
  db-data-homolog:
  redis_data_homolog:

networks:
  internal-homolog:
    driver: bridge
  web-network:
    external: true
